### ISSUE TITLE
Boot screen is text only after install Numix

### ISSUE THREAD

**Issue by deanpcmad** [captainsensible/xupdate#1]
Hey, I've been commenting on your Reddit post after a couple of issues I had where after running the script. I have a modified one for installing some Ruby development dependencies and some extra software.

When installing the Numix icons set, you choose to install `numix-*`. This also installs the `numix-plymouth-theme` package. After installing this the boot up screen is text only. After about an hour or 2 of playing around with the script to find out what it was it, I finally narrowed it down to the `numix-plymouth-theme` package. This package hasn't been updated for Ubuntu 16.04 because it shows this warning `W: plymouth module (/usr/lib/x86_64-linux-gnu/plymouth//.so) missing, skipping that theme.`

Please see this issue comment as it includes a fix. You can download the zip file attached and install the `numix-plymouth-theme` from there first before installing the others. 

https://github.com/numixproject/numix-plymouth-theme/issues/1#issuecomment-251371736

**Comment by captainsensible** [comment]
Thanks for the tip! I've removed numix-plymouth-theme by just installing 
numix-gtk-theme, numix-icon-theme, numix-icon-theme-circle, and numix-folders

**Comment by deanpcmad** [comment]
Yep that worked fine for me :)
